### ISSUE TITLE
Refactor the policy training code

### ISSUE THREAD

**Issue by marcelsan** [isl-org/OpenBot#201]
- [Done in #204] implement tf-records for more robust data loading.
- remove the duplicated code from Jupyter, WebServer backend, etc and use the openbot package.
- [Done in #204] upgrade to latest tensorflow version.
- make sure it works with Colab.

**Comment by thias15** [comment]
I think the only thing missing now, is a Colab version of the notebook.

**Comment by marcelsan** [comment]
Yes, I will do this over the weekend and create another PR. Thanks for pointing that out.
