### ISSUE TITLE
Add to documentation the steps of setting up autonomous navigation through obstacles

### ISSUE THREAD

**Issue by ajohansson-git** [isl-org/OpenBot#213]
The OpenBot Youtube video (at 3:00 and 3:17) demonstrates autonomous navigation, including through randomly placed obstacles.

Can I request a beginner-level how-to for setting this up (including training the model or using your pre-trained model, etc.)?

The arxiv paper's methodology description is perhaps not simple enough to reproduce (especially for those who are less experienced with Tensorflow, etc.).

Thank you.

**Comment by thias15** [comment]
We will look into this, but it may take some time. Can you see if the latest jupyter notebook on master makes it easier?

**Comment by thias15** [comment]
Please check out the [policy learning videos](https://github.com/isl-org/OpenBot/tree/master/body/lite#step-by-step-video-guides).
