### ISSUE TITLE
Taobao purchase links on CN version of `build your robot body` are unable to use

### ISSUE THREAD

**Issue by AmagiDDmxh** [isl-org/OpenBot#216]
**Describe the bug**

Links in the section of "料清单" are unable to open and use, which simply redirect to Taobao home page all the time whether I've logged in or not

PAGE LINK: https://github.com/isl-org/OpenBot/blob/master/body/README_CN.md

**To Reproduce**
1. Go to 'https://github.com/isl-org/OpenBot/blob/master/body/README_CN.md'
2. Click on any '淘宝购买' in “料清单” section
3. Open up Taobao link but non of any item detail page was shown

**Expected behavior**
Should open up a detailed HW item page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 92.0.4515.131

**Additional context**

Haven't found anything useful, the share link format of Taobao seems to change every year? Let me try to figure out this!

**Comment by thias15** [comment]
Can you fix it @leegang or @AmagiDDmxh and send a PR. In general the Chinese documentation is very updated and could really use an overhaul across the complete repo.

**Comment by thias15** [comment]
Anyone who can updated the Chinese links and documentation?
