### ISSUE TITLE
Point-goal navigation using ARCore

### ISSUE THREAD

**Issue by dvdhfnr** [isl-org/OpenBot#243]
- select goal by tapping on the screen (ARCore)
- specify the goal manually (polar coordinates)
- drive with trained policy

**Comment by alstjr510** [comment]
Hello! I'd like to use the Point Goal Navigation feature using ARCore! Install (ARCore_1_2_x86_for_emulator.apk) in the emulator, enter the OpenBot app, and run Point Goal Navigation, and the app will go down! Do you know what the problem is?
