### ISSUE TITLE
Upload error on arduino IDE

### ISSUE THREAD

**Issue by jony-g06** [isl-org/OpenBot#270]
I just downloaded the firmware file to my computer in order to get the code for the openbot and, after checking it, it gives an error on line 238 that says "'coast_mode' does not name a type", even though it is defined as a boolean on line 62 with a value of 1. What can I do to fix the error?

**Comment by thias15** [comment]
Which vehicle are you trying to compile for?

**Comment by jony-g06** [comment]
> 

The openbot that appears on the website

**Comment by quentin-leboutet** [comment]
Hi jony-g06, 
did you try moving the line 238 inside the **void setup()** scope ?  Something like:

```
void setup()
{
...
#if (OPENBOT == LITE)
  coast_mode = !coast_mode;
#endif
}
```
This solves the issue in my case.

**Comment by thias15** [comment]
Thanks @quentin-leboutet, I merged your PR. @jony-g06 can you pull again from master and try if it works for you?
