### ISSUE TITLE
Openbot hardware 

### ISSUE THREAD

**Issue by robotixdevteam** [isl-org/OpenBot#274]
Hi, We have used Arduino nano in our project with the old boot loader we cannot able to make it work in sense we are not able to replicate some of the functionalities of the openbot but we can make it work with Arduino uno.

**Comment by thias15** [comment]
We have used the Arduino Nano with old Bootloader for all experiments. What does not work for you?

**Comment by robotixdevteam** [comment]
The nano with old bootloader is not responding with the phone. can you help us through this?

**Comment by robotixdevteam** [comment]
Sorry, For now we are going ahead with the uno board which is working for us
