### ISSUE TITLE
video stream error

### ISSUE THREAD

**Issue by alstjr510** [isl-org/OpenBot#284]
**Describe the problem**
A clear and concise description of what the problem is or what information you are looking for.
It connects when I run (python keyboard-pygame.py --video), but the video doesn't come out of my laptop!

Can't read stream is an error message when running ( python keyboard-pygame.py --video)

I want to know the camera address information of the cell phone connected to the open bot.(On Openbot Application)

**To Reproduce**
1.conda activate [your env]
2.cd Openbot
3.cd controller
4.cd python
5. python keyboard-pygame.py --video

**Expected behavior**
A clear and concise description of what you expected to happen:
I can see the video of the cell phone camera connected to the open-bot app on my laptop.

**Screenshots**
If applicable, add screenshots to help explain your [problem.]

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser :  chrome
 - Version 18.04

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 12
 - Browser :chrome
 - Version : I didn't understand what version you were talking about.

**Additional context**

**Comment by thias15** [comment]
Did you choose RTSP in the settings of the OpenBot app?

**Comment by alstjr510** [comment]
> Did you choose RTSP in the settings of the OpenBot app?

Yes, I know that there are WebRTC and RTSP in Stream mode. And I set it to RTSP.

**Comment by thias15** [comment]
@izivkov any ideas?

**Comment by alstjr510** [comment]
Hello! I'm working on your open-bot project. There is one question.
Even if I update the app, Point Goal Navigation is not on the interface, but hasn't the function been added yet?

**Comment by alstjr510** [comment]
Yes, I know that there are WebRTC and RTSP in Stream mode. And I set it to RTSP. 
-----Original Message-----
