### ISSUE TITLE
Fast tracking a single person.

### ISSUE THREAD

**Issue by emo8899** [isl-org/OpenBot#286]
**Is your feature request related to a problem? Please describe.**
When I choose to follow people, if there is another person along the way, the car will randomly choose to follow one of them.

**Describe the solution you'd like**
Fast tracking a single person.

**Describe alternatives you've considered**

**Additional context**
https://github.com/foolwood/SiamMask

**Comment by thias15** [comment]
Yes, this is expected since it is currently using an off-the-shelf object detector. Would you like to contribute to the integration of an object tracker?

**Comment by emo8899** [comment]
> Yes, this is expected since it is currently using an off-the-shelf object detector. Would you like to contribute to the integration of an object tracker?

I'm really sorry. I really want to help you finish this work, but my professional ability is limited.

**Comment by thias15** [comment]
On hold for now.

**Comment by yudelex** [comment]
Is object tracking implemented in "Detector.java" file?
