### ISSUE TITLE
Current step show Failed 

### ISSUE THREAD

**Issue by emo8899** [isl-org/OpenBot#287]
**Describe the problem**
Current step show Failed after Current epoch(100%)&Training(100%)

**To Reproduce**
1. uploaded the training sources.
2. Move the training sources to Train datasets.
3. Go to Train and click the start(Use the default Settings.)

**Expected behavior**
Current step show Pass

**Screenshots**
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/108335283/176570418-32c5af35-57c8-488a-9b86-27f63a6df20f.png">
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/108335283/176570964-07c21808-fce9-47a6-bfcb-30343ad2b85f.png">

**Desktop (please complete the following information):**
 - OS: [MACOS(10.15.7 (19H1715))]
 - Browser [Edge]
 - Version [ 103.0.1264.37]

**Smartphone (please complete the following information):**
 - Device: [Huawei nova7 SE 5G]
 - OS: [Android 11]
 - Browser [n/a]
 - Version [0.6.0-openbot-master]

**Additional context**

**Comment by emo8899** [comment]
> How many epoch are you running. 
10times
Which version of tensorflow are you using?
tensorflow-2.9.1

**Comment by emo8899** [comment]
I try to set num epoch 50, error look the same.
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/108335283/176878604-0e67aafe-2041-4648-a452-45ae2873da44.png">

**Comment by thias15** [comment]
Can you try to replace `val_mean_absolute_error` with `val_mae`. It seems the name was changed. Alternatively, you could try an older version of tensorflow, e.g. 2.6.0.

**Comment by emo8899** [comment]
replace val_mean_absolute_error with val_mae not working, but I can successfully train using the method of a YouTube writer. It doesn't require your computer to have a lot of processing power, it uses Google Cloud computing to process data very quickly.  FYI!  https://www.youtube.com/watch?v=JMKPMcqvYKo

**Comment by thias15** [comment]
Any update on this @emo8899 ?

**Comment by emo8899** [comment]
i used the google driver to training robot, it's looks good.   a man who is a youtube author used Google Cloud computers to train the robots.

**Comment by thias15** [comment]
So did you manage to resolve the error?

**Comment by thias15** [comment]
@emo8899 it seems that this was resolved by using the Colab notebook. Is that correct? Will close for now, feel free to reopen if the issue persists.
