### ISSUE TITLE
firmware

### ISSUE THREAD

**Issue by mjanddy** [isl-org/OpenBot#293]
when I upload the firmware,it is error which that is some fuction is declared after. How should I fix it?
![image](https://user-images.githubusercontent.com/27938658/187137270-b56b1e04-afd8-4ef6-aeef-76f5cd014ad9.png)

**Comment by quentin-leboutet** [comment]
Hello mjanddy, 

thank you for using OpenBot !
Could you give us more information about the context in which you encounter this error so that we can reproduce it ?
For instance, on which board are you trying to flash this code ? 
Did you modify the firmware ? In which way ? 

Thank you 

Quentin

**Comment by quentin-leboutet** [comment]
Strange... I cannot reproduce your bug. Are you using the last IDE version ? What are your exact settings ?

**Comment by mjanddy** [comment]
> Strange... I cannot reproduce your bug. Are you using the last IDE version ? What are your exact settings ?

I use arduion ide 1.8.19; just as  github setting

**Comment by mjanddy** [comment]
> > Strange... I cannot reproduce your bug. Are you using the last IDE version ? What are your exact settings ?
> 
> I use arduion ide 1.8.19; just as github setting


> Strange... I cannot reproduce your bug. Are you using the last IDE version ? What are your exact settings ?

 and now  I moved the position of the function, but I'm not sure if it's correc

**Comment by quentin-leboutet** [comment]
Did you try compiling the firmware using the Arduino [cloud IDE](https://create.arduino.cc) ?

**Comment by mjanddy** [comment]
> the Arduino [cloud IDE](https://create.arduino.cc/editor) ?

ok,I will try it ,thanks!

**Comment by mjanddy** [comment]
> Did you try compiling the firmware using the Arduino [cloud IDE](https://create.arduino.cc/editor) ?

It is ok,thank you!
