### ISSUE TITLE
IOS support,

### ISSUE THREAD

**Issue by thebigboss84** [isl-org/OpenBot#294]
The documentations refers to IOS support is coming soon , do you have a timeline for this to come ? 

Thanks ,

**Comment by quentin-leboutet** [comment]
Hello Aboude , 

A prototype of the OpenBot app is indeed being developed and should be released to the public in a couple of months (probably in around 2-3 months). 

Regards

Quentin

**Comment by thebigboss84** [comment]
Well great news ! If you need a beta tester my car is built and ready to accept phone 😅

**Comment by thias15** [comment]
@thebigboss84 are you on Slack? We will announce the release there and ask for beta testers.
