### ISSUE TITLE
Is there already an existing .java file for using YOLOv7tiny in OpenBot?

### ISSUE THREAD

**Issue by RoBoFAU** [isl-org/OpenBot#334]
I want to use my custom trained yolov7 tiny model in Openbot.

Can someone help me with the functions/parameters in the java script required for using that model?

**Comment by thias15** [comment]
Are you able to convert into tflite? What does the input and output look like? Are you using the standard Coco labelmap?

**Comment by RoBoFAU** [comment]
yes, it is already converted to tflite and I am using the standard coco labelmap.

Which information do you need about input/output?

**Comment by thias15** [comment]
Duplicate of #335
