### ISSUE TITLE
Unpowered arduino nano

### ISSUE THREAD

**Issue by rfedersp** [isl-org/OpenBot#354]
Hi, I'm a total beginner in electronics and I'm trying to build the DIY version of OpenBot (which is a great project!). The problem is that I can't power the Arduino Nano with the voltage divider bridge... Is my assembly wrong?

![20230425_223412](https://user-images.githubusercontent.com/59554513/234624256-05ea9600-446d-45eb-b707-a204676a3d99.jpg)

**Comment by thias15** [comment]
Hard to tell from the image but looks roughly ok. Can you measure the voltage with a multimeter? Note that if you built the voltage divider as per instructions and connected it to the corresponding pins the purpose is not to power the Arduino but to measure the battery voltage. The Arduino is powered via the USB connection to the phone.

**Comment by rfedersp** [comment]
I measure a voltage of 0.6 but it must be normal if it is not intended to power the arduino.  
On the other hand, when I connect my phone to the arduino, no led lights up, is that normal?

**Comment by rfedersp** [comment]
The problem was with my OTG cable... Everything works now! 
Thank you for your help :)
