### ISSUE TITLE
Unable to Connect Android App Openbot to Controller App

### ISSUE THREAD

**Issue by A-janjan** [isl-org/OpenBot#377]
I have encountered an issue where the Openbot app is unable to connect to the Controller app. I have installed both of them and connected them to the same network, but they aren't connected to each other. Additionally, I have changed the controller type to phone.

What should I do?

Is there any log?

**Comment by Eashika2504** [comment]
Make sure to open the controller app first and then connect to OpenBot by switching the controller mode to phone. If you're still facing issues, consider switching to a different device.

**Comment by A-janjan** [comment]
It didn't work for 3 devices;  Are there any logs or things that can show me what happened backstage?

**Comment by hardikgarg02** [comment]
Yes, When successful connection establishes, in robot app log appears  as  "Client connected: <IPv6 link-local address of wifi>".   And if there comes any error it shows "Got exception: <error> ".

**Comment by abhijeetmhatre** [comment]
I am also facing the same issue. 

The setup is pixel6a(controller) running a WiFi hotspot. Samsung Galaxy M31(robot) and also a laptop. Tried reversing the two phones. Also tried  third phone hosting the hotspot instead of one of the  two

 I am able to control the car using the python scripts. in laptop but not with the controller app.

**Comment by M-S-10** [comment]
It works fine for me! Make sure that both the phones are on the same WiFi Network.

**Comment by A-janjan** [comment]
Thanks

**Comment by M-S-10** [comment]
Did it work? if yes then please close this issue.

**Comment by A-janjan** [comment]
Yeah, but the main solution is changing the stream mode from RTSP to WebRTC. Thanks to all.
