### ISSUE TITLE
Running without stopping

### ISSUE THREAD

**Issue by A-janjan** [isl-org/OpenBot#378]
When I go to the Robot info section and then click the forward or backward command in the send command section, I see that my motors start running without stopping. Additionally, when I click stop, nothing changes.

I use POCO X3 Pro.

**Comment by hardikgarg02** [comment]
Please ensure that the app maintains a stable Bluetooth connection with the robot, without any disconnections between commands.

**Comment by A-janjan** [comment]
No, I didn't use Bluetooth. I just used the main application and the following sections:

![openbot_err1](https://github.com/isl-org/OpenBot/assets/62621376/83357932-faa7-4811-a4ea-3abdb23cd104)

**Comment by A-janjan** [comment]
I did the firmware testing with an Arduino serial monitor, and at first, I sent, for example, c100,100 and then the motors started running. but after I sent c0,0 and the motors didn't stop. I don't know why motors can't be stopped.

**Comment by Eashika2504** [comment]
Ensure that your motor connections are accurate, and double-check that the specified serial pin numbers in the code align with the actual hardware configuration.

**Comment by A-janjan** [comment]
ok

**Comment by A-janjan** [comment]
After I sent a command via a serial monitor (e.g., c50,0), the motors moved correctly, but the serial connection disconnected, and I couldn't send a new command.

**Comment by A-janjan** [comment]
The main problem arises when I enable #define HAS_OLED 1 in the DIY body firmware. Consequently, other commands fail to send correctly. However, after disabling the OLED, everything is fixed.
