### ISSUE TITLE
Problem in connection to node-js controller

### ISSUE THREAD

**Issue by A-janjan** [isl-org/OpenBot#401]
I have a problem connecting to the robot via the node-js controller in Ubuntu. I connected them to the same network but nothing happened. What should I do?

These are my terminal logs:

![Screenshot from 2024-03-09 01-12-19](https://github.com/isl-org/OpenBot/assets/62621376/e4dbe824-8917-465f-bc7f-ef2b2fbda62e)

**Comment by hardikgarg02** [comment]
On Connecting to phone, is web interface opening on the local ? And if not try to switch the control mode to phone.

**Comment by A-janjan** [comment]
Ok, thanks.

**Comment by iwl** [comment]
[New Version](https://github.com/ob-f/OpenBot/issues/490#issuecomment-4313665716)
