### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dinushan4568** [isl-org/OpenBot#456]
error Unable to open base configuration reference file '/Users/dinushanlakshitha/MyFirstRNProject/ios/Pods/Target Support Files/Pods-MyFirstRNProject/Pods-MyFirstRNProject.debug.xcconfig'. (in target 'MyFirstRNProject' from project 'MyFirstRNProject')
error Unable to load contents of file list: '/Target Support Files/Pods-MyFirstRNProject/Pods-MyFirstRNProject-frameworks-Debug-input-files.xcfilelist' (in target 'MyFirstRNProject' from project 'MyFirstRNProject')
error Unable to load contents of file list: '/Target Support Files/Pods-MyFirstRNProject/Pods-MyFirstRNProject-frameworks-Debug-output-files.xcfilelist' (in target 'MyFirstRNProject' from project 'MyFirstRNProject')
error Unable to load contents of file list: '/Target Support Files/Pods-MyFirstRNProject/Pods-MyFirstRNProject-resources-Debug-input-files.xcfilelist' (in target 'MyFirstRNProject' from project 'MyFirstRNProject')
error Unable to load contents of file list: '/Target Support Files/Pods-MyFirstRNProject/Pods-MyFirstRNProject-resources-Debug-output-files.xcfilelist' (in target 'MyFirstRNProject' from project 'MyFirstRNProject')
error Failed to build ios project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'MyFirstRNProject.xcodeproj'.

**Comment by isha382** [comment]
Hi @Dinushan4568 , you can try configure your own independent account for building the app - iOS as shown in the below attachment.
![Uploading img.png…](img)
please refer [ios support](https://github.com/isl-org/OpenBot/blob/master/ios/README.md) for more information
